[tool.poetry]
name = "uniprotparser"
version = "1.0.0"
description = "Getting Uniprot Data from Uniprot Accession ID through Uniprot REST API"
authors = ["Toan Phung <toan.phungkhoiquoctoan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

